openapi: 3.0.3 

info: 

  title: Vinci Stock eXchange 

  description: place boursière  

  version: 1.0.0 

servers: 

  - url: http://localhost:9001 

    description: Development server 

paths: 

/accounts: 

post: 
      summary: Créer un compte 
      requestBody: 
        description: Le compte à créer 
        content: 
          'application/json': 
            schema: 
              $ref:'#/components/schemas/account 

      responses: 
        409: 
          description: Le compte existe déjà 
          content: 
            'application/json': 
              schema: 
                $ref: '#/components/schemas/account' 

    get: 
      summary: Lire tous les comptes 
      description: Récupère la liste des comptes des investisseurs. 
      responses: 
        200: 
          description: Retourne la liste de tous les comptes 
          content: 
            'application/json': 
              schema: 
                type: array 
                items: 
                  $ref: '#/components/schemas/account' 

/accounts/{id}: 
    parameters: 
      - name: id 
        in: path 
        description: id du compte 
        required: true 
        schema: 
          type: string 
          example: 1 
        style: simple 

    get: 
      summary: Lire le compte 
      responses: 
        404: 
          description: Le compte est inexistant 
        200: 
          description: Retourne le compte 
          content: 
            'application/json': 
              schema: 
                $ref: '#/components/schemas/account'
    put: 
      summary: Mise à jour du compte 
      requestBody: 
        description: Nouvelles valeurs du compte 
        content: 
          'application/json': 

            schema: 

              $ref: '#/components/schemas/account'

      responses: 
        400: 
          description: Aucun match avec l’id du compte 
        404: 
          description: Le compte est inexistant 
        200: 
          description: Updated product, returned old values 
          content: 
            'application/json': 
              schema: 
                $ref: '#/components/schemas/account' 

    delete: 
      summary: Supprimer le compte 
      responses: 
        404: 
          description: Le compte est inexistant 
        200: 
          description: Compte supprimé 

